/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TransactionIndexDTO
 */
export interface TransactionIndexDTO {
    /**
     * 
     * @type {string}
     * @memberof TransactionIndexDTO
     */
    transactionId: string;
    /**
     * 
     * @type {number}
     * @memberof TransactionIndexDTO
     */
    decimalAmount: number;
    /**
     * 
     * @type {string}
     * @memberof TransactionIndexDTO
     */
    comment?: string;
}

/**
 * Check if a given object implements the TransactionIndexDTO interface.
 */
export function instanceOfTransactionIndexDTO(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "transactionId" in value;
    isInstance = isInstance && "decimalAmount" in value;

    return isInstance;
}

export function TransactionIndexDTOFromJSON(json: any): TransactionIndexDTO {
    return TransactionIndexDTOFromJSONTyped(json, false);
}

export function TransactionIndexDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): TransactionIndexDTO {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'transactionId': json['transactionId'],
        'decimalAmount': json['decimalAmount'],
        'comment': !exists(json, 'comment') ? undefined : json['comment'],
    };
}

export function TransactionIndexDTOToJSON(value?: TransactionIndexDTO | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'transactionId': value.transactionId,
        'decimalAmount': value.decimalAmount,
        'comment': value.comment,
    };
}

