/* tslint:disable */
/* eslint-disable */
/**
 * BankWiz API
 * An API for accessing banking functionalities provided by BankWiz
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UpdateTransactionRequest
 */
export interface UpdateTransactionRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateTransactionRequest
     */
    decimalAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateTransactionRequest
     */
    comment?: string;
}

/**
 * Check if a given object implements the UpdateTransactionRequest interface.
 */
export function instanceOfUpdateTransactionRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function UpdateTransactionRequestFromJSON(json: any): UpdateTransactionRequest {
    return UpdateTransactionRequestFromJSONTyped(json, false);
}

export function UpdateTransactionRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTransactionRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'decimalAmount': !exists(json, 'DecimalAmount') ? undefined : json['DecimalAmount'],
        'comment': !exists(json, 'Comment') ? undefined : json['Comment'],
    };
}

export function UpdateTransactionRequestToJSON(value?: UpdateTransactionRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'DecimalAmount': value.decimalAmount,
        'Comment': value.comment,
    };
}

