name: Branch CI
on:
  push:
    branches:
      - master
      - develop
env:
  USER_GITHUB_KEY: ${{ secrets.GITHUB_TOKEN }}
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  CI: true
  NEXT_TELEMETRY_DISABLED: 1
jobs:
  package_application:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: PNPM Clean install
        run: pnpm install
      - name: PNPM Run lint
        run: pnpm run lint
      - name: PNPM Run prettier
        run: pnpm run prettier
      - name: PNPM Run build
        run: pnpm run build
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
