---
name: Pull Request CI
"on":
  push:
    branches:
      - develop
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref }}"
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup action
        uses: ./.github/actions/setup-env
      - name: PNPM Run build
        run: pnpm run build
  sonar:
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup action
        uses: ./.github/actions/setup-env
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  publish:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      deployments: write
    needs:
      - sonar
    name: Publish to Cloudflare Pages
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup action
        uses: ./.github/actions/setup-env
      - name: PNPM Run build
        run: pnpm run build
        env:
          VITE_AUDIENCE_AUTH0: ${{ vars.VITE_AUDIENCE_AUTH0 }}
          VITE_DOMAIN_AUTH0: ${{ vars.VITE_DOMAIN_AUTH0 }}
          VITE_SERVER_URL: ${{ vars.VITE_SERVER_URL }}
          VITE_CLIENT_ID_AUTH0: ${{ secrets.VITE_CLIENT_ID_AUTH0 }}
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: bankwiz-frontend-dev
          directory: dist
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Switch what branch you are publishing to.
          branch: ${{ github.ref_name }}
          # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
          wranglerPagesDeploy: '3'