---
name: Pull Request CI
"on":
  pull_request:
    branches:
      - develop
concurrency:
  group: "${{ github.workflow }}-${{ github.head_ref }}"
  cancel-in-progress: true
jobs:
  check-eslint:
    runs-on: ubuntu-22.04
    name: Check eslint
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup action
        uses: ./.github/actions/setup-env
      - name: PNPM Run lint
        run: pnpm run lint:check
  check-prettier:
    runs-on: ubuntu-22.04
    name: Check prettier
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup action
        uses: ./.github/actions/setup-env
      - name: PNPM Run lint
        run: pnpm run format:check
  build:
    runs-on: ubuntu-22.04
    name: Build
    needs:
      - check-eslint
      - check-prettier
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup action
        uses: ./.github/actions/setup-env
      - name: PNPM Run build
        run: pnpm run build
  sonar:
    runs-on: ubuntu-22.04
    name: Sonar
    needs:
      - build
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup action
        uses: ./.github/actions/setup-env
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}