name: Pull Request CI
on:
  pull_request:
    branches:
      - develop
env:
  USER_GITHUB_KEY: ${{ secrets.GITHUB_TOKEN }}
  CI: true
  NEXT_TELEMETRY_DISABLED: 1
jobs:
  check-eslint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Pnpm setup
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: PNPM Clean install
        run: pnpm install
      - name: PNPM Run lint
        run: pnpm run lint
  check-prettier:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: PNPM Clean install
        run: pnpm install
      - name: PNPM Run prettier
        run: pnpm run prettier
  build:
    runs-on: ubuntu-22.04
    needs:
      - check-eslint
      - check-prettier
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'pnpm'
      - name: PNPM Clean install
        run: pnpm install
      - name: PNPM Run build
        run: pnpm run build
  sonar:
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
